- build/patches/Update-i18n-zh_CN-support.patch
- Add translation for `View source` introduced by v84.0.4147.90.
- Remove `About Bromite` translation from `chromium_strings_zh-CN.xtb` since it never works.
> Update zh_CN translations

- build/bromite_patches_list.txt
- build/patches/Add-a-flag-to-always-view-desktop-site-for-all-websites.patch
fix #780 
we have to choose where to put the flag:
in site setting: +4 files
In homepage settings: +2 files
in my opinion last is better because that flag is linked to the tab.
that is, if I change the flag I have to close the tab, otherwise it does not take the change.
> Add flag to always view the desktop site for all websites

- build/bromite_patches_list.txt
- build/patches/Add-query-all-packages-permission-for-R.patch
See https://github.com/brave/brave-browser/issues/12330 for more details.
I was experiencing this issue for the past week on my new Pixel 5 running ProtonAOSP, and can confirm the new `QUERY_ALL_PACKAGES` permission resolved the issue.
I see there's currently 5 other patches that target `chrome/android/java/AndroidManifest.xml`, so feel free to reject this requested approach if you think there's a better way to add the permission -- whatever's easiest to maintain.
Sidebar: Google Chrome's official builds seem to have already added this permission, but they overlooked porting it back to Chromium. Wouldn't be surprised if it got forgotten during all the recent build targets shuffling
> Intent handling fix for local apps on Android 11

- build/patches/Add-a-proxy-configuration-page.patch
The current patch comes from the implementation for ChromeOS which gets the proxy information from the local_state for the system network context.
This is not completely correct in Android, since the network context is never connected to any user profile and only gets the proxy information from the system.
With this change settings are moved from the Profile to LocalState, allowing the transparent use of the proxy also for SimpleURLLoaders (for example used for downloading Adblock filters and for favicons, which currently do not use any proxy even if set). Existing settings are automatically migrated on first startup.
> Enable proxy config for the system network context

- build/patches/Disable-the-DIAL-repeating-discovery.patch
This PR adds a fix to the DIAL repeating discovery patch to resolve a potential crash when the network state changes.
> Update DIAL repeating discovery patch

- build/patches/JIT-less-toggle.patch
Currently the SystemWebView fails a CTS test case, specifically
testStrictMode from WebViewHostSideStartupTest, due to StrictMode
warnings. So ignore the StrictMode warning as is done elsewhere.
> Ignore StrictMode warning

- README.md
Images used as shields are expected to work as hyperlinks to relevant urls.
They weren't.
Now they should be.
Alternative: Use shields.io, they provide high-res, auto-updated shield images.
Try the below:
[![GitHub release (latest SemVer)](https://img.shields.io/github/v/release/bromite/bromite?logo=github)](https://github.com/bromite/bromite/releases/latest) [![GitHub license](https://img.shields.io/github/license/bromite/bromite)](https://github.com/bromite/bromite/blob/master/LICENSE)
Downside is, without adding Shields.io app to the project, you might hit GitHub rate limits. By adding it it can be mitigated freely.
Note that Shields.io itself is also an opensource project without any tracking, so that won't be much of a problem.
> Make image shields more useful

- build/bromite_patches_list.txt
- build/chromium_patches_list.txt
- build/patches/disable-broken-warning-for-auto-var-init.patch
- build/patches/enable-ftrivial-auto-var-init-zero.patch
Build with '-ftrivial-auto-var-init=zero' ~~and enable 'Strict Origin Isolation' by default~~.
Fix for #1749
> Enable trivial auto var init

- build/patches/Disable-third-party-origin-trials.patch
based on the research I have done, unfortunately it is still possible to activate origin trials.
in particular, the static method `TrialTokenValidator::IsTrialPossibleOnOrigin()` must be disabled.
also the assumption that I had made about the source is not correct, so it is necessary to inhibit also `ProcessHttpEquivOriginTrial`
> Fix another way to activate origin trials

- build/patches/Client-hints-overrides.patch
I make you the proposal to completely disable client hints, since they would make it possible to make the purposes of the ua reduction ineffective.
in particular, the management of accept ch in the always incognito mode, which by keeping the requests of the sites in the content settings, would allow to know if a user has already visited the site in the same session.
currently the management of client hints is under development and therefore it could be possible that the patch will need to be revised over time.
> Proposal: complete disabling of client hints

- build/patches/Enable-StrictOriginIsolation-and-SitePerProcess-flags.patch
- build/patches/Site-setting-for-javascript-jit.patch
here is a possible patch for activating the site setting for jit.
to make it work it is necessary to activate `kStrictOriginIsolation` and `kSitePerProcess` otherwise the setting would only work with the scheme and eTLD+1.
I tried for almost a month on my 2gb memory cell phone, not detecting any problems.
fix for #1720
> Implement jit toggle patch

- build/patches/Remove-contextual-search-manager.patch
As mentioned in https://github.com/bromite/bromite/commit/47d0d4f9f8e3443a2204f7bbebcd83b068d6debd#commitcomment-69463652, this is needed to avoid the following build error:
```
[41721/51515] CXX obj/content/browser/browser/browser_interface_binders.o
FAILED: obj/content/browser/browser/browser_interface_binders.o 
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/content/browser/browser/browser_interface_binders.o.d -DOFFICIAL_BUILD -D_GNU_SOURCE -DANDROID -DHAVE_SYS_UIO_H -DANDROID_NDK_VERSION_ROLL=r22_1 -DCR_CLANG_REVISION=\"llvmorg-14-init-12719-gc4b45eeb-3\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD …
```
> Fix for contextual search manager removal patch

- build/patches/Add-lifetime-options-permissions.patch
I'm sorry, but my patches seem to get more and more complex along the time...
I try to explain the applied logics, ask me if I'm not clear.
this patch takes advantage of the possibility to indicate the session mode for content-settings: in fact in chromium it is possible to specify the constraint `content_settings::SessionModel` as `UserSession` when setting the value, even choosing a possible expiration time.
The logics I have seen with the ClientHints but it seems that chromium exploits this possibility when it is necessary to maintain a specific value by origin.
In any case, all content settings of this type are not saved on disk, allowing you to reset the status each time the application is restarted.
The patch acts on these points:
- components/content_settings
defines a new …
> Add lifetime options support for permissions

- build/patches/Add-an-always-incognito-mode.patch
Modified the patch not to save WebsiteSettings other than ContentSettings in always incognito mode.
Fix for #1942
> Don't save WebsiteSettings if it's not a ContentSetting

- build/patches/Add-webgl-site-setting.patch
- build/patches/Content-settings-infrastructure.patch
this pull contains two different patches:
- Content-settings-infrastructure.patch
it is a "small" utility that allows me to have less effort in adding a new site setting in chromium, considering that every time there are always the same points to touch.
the advantage of using it may be even more evident if we changed all the other patches to use this one.
explanations are in the included readme
- Add-webgl-site-setting.patch
trivially it adds a site setting related to webgl default disabled. in the patch there is actually only the implementation, since the ui is handled by the patch from before.
you can see the various changes with https://uazo.github.io/superpatch/bromite/pull/2045
> Add webgl site setting

- README.md
It was apparently renamed at some point but not reflected here.
> Fix incognito screenshots flag name

- build/patches/Follow-only-system-dark-mode.patch
Unlike other apps, when Chromium-based Android browsers are configured to follow system dark mode preference, they ignore the actual system preference and respect battery saver mode first of all, while most users always have power saving mode enabled, making this setting useless.
This patch forces Chromium to ignore power saving mode when choosing a theme, making its behavior consistent with the rest of the apps, including the system and Google apps that follow actual system theme on Android 10 and above in the first place.
> Patch for allowing to match only system dark mode

- build/patches/Remove-window-name-on-cross-origin-navigation.patch
this is a simple revert of [Revert Implemented: remove browsing context name on cross origin navigation](https://source.chromium.org/chromium/chromium/src/+/a9d3e8b258ba21d310bf7456cd4c270e3d49e820)
```
When updating the history after a cross-origin navigation, the HTML
Standard says: "If the browsing context is a top-level browsing context,
but not an auxiliary browsing context, then set the browsing context's
name to the empty string."
Currently we are not doing this which means there's potential
information leak.
```
Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=706350
Spec: https://html.spec.whatwg.org/multipage/browsers.html#resetBCName
Web Test: https://wpt.fyi/results/html/browsers/windows/clear-window-name.https.html?label=master&label=experimental&aligned
> Reason …
> Remove window name on cross origin navigation

- build/patches/Timezone-customization.patch
Due to the incorrect location (who knows why I put it there), the timezone override was immediately reset making the patch useless.
> Fix incorrect handling of blink::TimeZoneController::TimeZoneOverride

- build/patches/Remove-navigator-connection-info.patch
since it is a fingerprinting surface, it makes sense to remove the result of `navigator.connection`
> Remove navigator.connection info

- build/patches/Multiple-fingerprinting-mitigations.patch
Adds a mitigation to scripts that use svg to generate hashes for the device fingerprint
> Add svg fingerprinting mitigation
